/*
 * Nsmaf_EventExposure
 *
 * Session Management Event Exposure Service API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SmafEvent string

// List of SmafEvent
const (
	SmafEvent_AC_TY_CH    SmafEvent = "AC_TY_CH"
	SmafEvent_UP_PATH_CH  SmafEvent = "UP_PATH_CH"
	SmafEvent_PDU_SES_REL SmafEvent = "PDU_SES_REL"
	SmafEvent_PLMN_CH     SmafEvent = "PLMN_CH"
	SmafEvent_UE_IP_CH    SmafEvent = "UE_IP_CH"
)
