/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"free5gc/src/app"
	"free5gc/src/smaf/logger"
	"free5gc/src/smaf/service"
	"free5gc/src/smaf/version"
	"os"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)

var SMAF = &service.SMAF{}

var appLog *logrus.Entry

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "smaf"
	fmt.Print(app.Name, "\n")
	appLog.Infoln("SMAF version: ", version.GetVersion())
	app.Usage = "-free5gccfg common configuration file -smafcfg smaf configuration file"
	app.Action = action
	app.Flags = SMAF.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		logger.AppLog.Errorf("SMAF Run error: %v", err)
	}
}

func action(c *cli.Context) {
	app.AppInitializeWillInitialize(c.String("free5gccfg"))
	SMAF.Initialize(c)
	SMAF.Start()
}
